# .github/workflows/ci-cd.yaml
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r app/requirements.txt

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/movie-api:latest ./app
          docker push ghcr.io/${{ github.repository }}/movie-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml
